// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Findier.Api.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Threads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Threads));
        
        string IMigrationMetadata.Id
        {
            get { return "201602220045439_Threads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
