// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Findier.Api.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EnableMessaging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnableMessaging));
        
        string IMigrationMetadata.Id
        {
            get { return "201602220015257_EnableMessaging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
